on: push
name: Static Analysis
jobs:
  test:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: mkdir -p assets && echo "${{ secrets.keys_json }}" > assets/keys.json
    - run: flutter analyze