on: push
name: Unit and Widget Tests
jobs:
  test:
    name: Unit and Widget Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: mkdir assets && echo "${{ secrets.keys_json }}" > assets/keys.json
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/lcov.info